### ISSUE TITLE
Create uniref90 compressed database ERROR

### ISSUE THREAD

**Issue by zhxd2** [ndaniels/MICA#3]
Hi,
I need to compress the uniref90 database, which contains 35218174 sequences。 After running 50 hours, finally exit with "out of memory" ERROR。

How could I speed up this step?

How to avoid the ERROR ?

thanks !

**Comment by dcdanko** [comment]
What kind of machine are you running on?

I believe you can reduce memory requirements by reducing the size of seed
table mica uses for compression

**Comment by dcdanko** [comment]
For posterity:

The database compression step is fairly slow and memory intensive. We aim to provide commonly used databases for public download. If you're having trouble compressing a database let us know and we will work to make the database publicly available.
