### ISSUE TITLE
Error converting diamond output to blast tabular

### ISSUE THREAD

**Issue by jfroula** [ndaniels/MICA#4]
Hi,
I'm getting an error 
`Error processing queries: Error converting diamond output to blast tabular: %!s(MISSING)`

To test mica's blastx function I created a test set using some contigs I had lying around.  I used prodigal to predict the proteins from these contigs and compressed them to form the database.  I then used the first contig as the query. (see attached).

cmds to duplicate error:

```
mica-compress --match-seq-id-threshold 60 --ext-seed-size 0 --ext-seq-id-threshold 50 --max-seeds 20 -p 40 testdb short.faa
mica-xsearch --dmnd-fine=result.txt testdb test.fasta
```

If I run blastx using the same query("test.fasta") and protein file("short.faa") for the database, I get the expected query hitting itself.

```
makeblastdb -dbtype prot -in short.faa
blastx -query test.fasta -db short.faa -outfmt '6 qseqid sseqid pident length qlen slen evalue bitscore' -out test.blastx  -max_target_seqs 1
```

`Scaffold2.1.1-9897.test Scaffold2.1.1-9897_1_3  100.00  389     3600    389     0.0     780`

Any advice?  
Thanks

[test.zip](https://github.com/ndaniels/MICA/files/203497/test.zip)

**Comment by jfroula** [comment]
By the way, I'm using 
blast+/2.2.31
diamond/0.7.1

and MICA github download from march 30th.

**Comment by ndaniels** [comment]
We will look into the problem. Can you tell us what version of diamond you are using?

**Comment by jfroula** [comment]
I was using diamond/0.7.1 and then I saw that you were testing on 0.7.9 so I loaded that version and got different error using the same commands above.

New Error:

cmd: mica-xsearch --dmnd-fine=result.txt testdb test.fasta  
Error diamond-blasting (x-search) fine database: Error opening diamond output: open result.txt: no such file or directory

however, if I don't use "--dmnd-fine=result.txt" then I get the expected output.

**Comment by ndaniels** [comment]
Yes, it seems that diamond changed its interface between those two versions, though it's not documented. We will look into what's going on with the —dmnd-fine argument. Thanks for letting us know!

**Comment by dcdanko** [comment]
Yes, I think I actually fixed this issue on the (new) query-compression
branch. I'll check and move the appropriate fixes to master today.

**Comment by dcdanko** [comment]
I believe the issue should be fixed. If the problem persists let me know and I'll deal with it ASAP.

You should continue to use diamond 0.7.9, the interface for diamond has changed between versions so diamond 0.7.1 won't work.

**Comment by dcdanko** [comment]
@jfroula, I'm assuming the fix worked and I'm closing the issue. If the fix didn't work let us know.
